Bugfix

diff --git a/calcVolume_vdW b/calcVolume_vdW
--- a/calcVolume_vdW
+++ b/calcVolume_vdW
@@ -29,111 +29,112 @@ FILE=$1
 
 while getopts "hE:N:f:" OPTION
 do
-    case $OPTION in
-		h)
-			cat "$PATHSCRIPTS/help_calcVolume_vdW.txt" 
-#			echo "Help-File does not exist (yet)".
-			exit 10
-		;;
-		f) FILE=$OPTARG
-		;;
-		E) EPSTAB=$OPTARG
-		;;
-		N) NPERM=$OPTARG
-		;;
-		*)
-			echo -e "Nonexistent flag.\033[31m Aborting.\033[0m"
-			exit 10
-		;;
-    esac
-done 
+	    case $OPTION in
+		    		h)
+								cat "$PATHSCRIPTS/help_calcVolume_vdW.txt" 
+								#			echo "Help-File does not exist (yet)".
+											exit 10
+													;;
+															f) FILE=$OPTARG
+																		;;
+																				E) EPSTAB=$OPTARG
+																							;;
+																									N) NPERM=$OPTARG
+																												;;
+																														*)
+																																		echo -e "Nonexistent flag.\033[31m Aborting.\033[0m"
+																																					exit 10
+																																							;;
+																																							    esac
+																																						    done 
 
-#RadiiLib="$PATHSCRIPTS/vdW-Radii-library.txt" #### Path of vdW-Radii library
-RadiiLib=$(find $PATHSCRIPTS/ -name "lib_*vdW*Radii*.txt" | head -1) #### Path of vdW-Radii library
-if [ ! -f $RadiiLib ]; then echo -e "\033[31mLibrary for vdW-Radii not found! Aborting.\033[0m"; exit 10; fi
-if [ ! -f $FILE ]; then echo -e "\033[31mInput-File does not exist! Aborting.\033[0m"; exit 10; fi
-SUFFIX=$(echo $FILE | rev | cut -f1 -d'.' | rev)
+																																						    #RadiiLib="$PATHSCRIPTS/vdW-Radii-library.txt" #### Path of vdW-Radii library
+																																						    RadiiLib=$(find $PATHSCRIPTS/ -name "lib_*vdW*Radii*.txt" | head -1) #### Path of vdW-Radii library
+																																						    if [ ! -f $RadiiLib ]; then echo -e "\033[31mLibrary for vdW-Radii not found! Aborting.\033[0m"; exit 10; fi
+																																						    if [ ! -f $FILE ]; then echo -e "\033[31mInput-File does not exist! Aborting.\033[0m"; exit 10; fi
+																																						    SUFFIX=$(echo $FILE | rev | cut -f1 -d'.' | rev)
 
-################### valid formats: XYZ and OUT
-case $SUFFIX in
-	xyz)
-		XYZFILE=$FILE
-	;;
-	out)
-		out2xyz $FILE
-		XYZFILE=$(echo $FILE | sed 's/.out/.xyz/')
-	;;
-	\?)
-		echo -e "\033[31mInvalid Format! Aborting.\033[0m"
-		exit 128
-	;;
-esac
+																																						    ################### valid formats: XYZ and OUT
+																																						    case $SUFFIX in
+																																							    	xyz)
+																																											XYZFILE=$FILE
+																																												;;
+																																													out)
+																																																out2xyz $FILE
+																																																		XYZFILE=$(echo $FILE | sed 's/.out/.xyz/')
+																																																			;;
+																																																				\?)
+																																																							echo -e "\033[31mInvalid Format! Aborting.\033[0m"
+																																																									exit 128
+																																																										;;
+																																																								esac
 
-#################### ensure having a XYZ-file in XMOL-format
+																																																								#################### ensure having a XYZ-file in XMOL-format
 
-CHECK=$(tail -1 $XYZFILE | awk '{print NF}')
-while [[ $CHECK -ne 4 ]]; do
-	sed -i "$"d $XYZFILE
-	CHECK=$(tail -1 $XYZFILE | awk '{print NF}')
-done
-sed -i 's/^[ \t]*//' $XYZFILE ### remove all leading spaces
-CHECK=$(head -1 $XYZFILE | tr -d '\r')
-re='^([0-9])+\s*$'
-if ! [[ $CHECK =~ $re ]]; then echo -e "\033[31mInvalid XYZ-format! First line must contain the number of atoms.\nAborting.\033[0m"; exit 1; fi
-((CHECK+=2))
-linenumber=$(wc -l $XYZFILE | awk '{print $1}')
-if ! [[ "$CHECK" = "$linenumber" ]]; then echo -e "\033[31mInvalid XYZ-format! First line must contain the number of atoms.\nCoordinates must start from 3rd line.\nAborting.\033[0m"; exit 1; fi
-re='^[A-Z][a-z]?(\s+[-]?[0-9]*\.[0-9]*){3}(\s+[A-Z][a-z]?(\s+[-]?[0-9]*\.[0-9]*){3})*\s*$' #### required format (case-sensitive Element Symbol followed by coordinates)
-CHECK=$(sed -n 3,"$linenumber"p $XYZFILE)
-if ! [[ $CHECK =~ $re ]]; then echo -e "\033[31mInvalid XYZ-format!\nRequirement: [Element Symbol] [x] [y] [z]\nAborting.\033[0m"; exit 128; fi
-NUMAT=$(echo "$linenumber-2" | bc -l) ### number of atoms
+																																																								CHECK=$(tail -1 $XYZFILE | awk '{print NF}')
+																																																								while [[ $CHECK -ne 4 ]]; do
+																																																										sed -i "$"d $XYZFILE
+																																																											CHECK=$(tail -1 $XYZFILE | awk '{print NF}')
+																																																										done
+																																																										sed -i 's/^[ \t]*//' $XYZFILE ### remove all leading spaces
+																																																										CHECK=$(head -1 $XYZFILE | tr -d '\r')
+																																																										re='^([0-9])+\s*$'
+																																																										if ! [[ $CHECK =~ $re ]]; then echo -e "\033[31mInvalid XYZ-format! First line must contain the number of atoms.\nAborting.\033[0m"; exit 1; fi
+																																																										((CHECK+=2))
+																																																										linenumber=$(wc -l $XYZFILE | awk '{print $1}')
+																																																										if ! [[ "$CHECK" = "$linenumber" ]]; then echo -e "\033[31mInvalid XYZ-format! First line must contain the number of atoms.\nCoordinates must start from 3rd line.\nAborting.\033[0m"; exit 1; fi
+																																																										re='^[A-Z][a-z]?(\s+[-]?[0-9]*\.[0-9]*){3}(\s+[A-Z][a-z]?(\s+[-]?[0-9]*\.[0-9]*){3})*\s*$' #### required format (case-sensitive Element Symbol followed by coordinates)
+																																																										CHECK=$(sed -n 3,"$linenumber"p $XYZFILE)
+																																																										if ! [[ $CHECK =~ $re ]]; then echo -e "\033[31mInvalid XYZ-format!\nRequirement: [Element Symbol] [x] [y] [z]\nAborting.\033[0m"; exit 128; fi
+																																																										NUMAT=$(echo "$linenumber-2" | bc -l) ### number of atoms
 
-#### write input-file for bin.ASV.1.3.11.linux64.intel (vdW-volume)
-Radii=$(cat $RadiiLib | sed '1d' | awk '{print $2 "=" $3}')
-echo -e "XYZ\n$XYZFILE\n1" > $vdWInput			### Specify Input-File
-echo $Radii >> $vdWInput						### read vdW-Radii from Library
-echo -e "$NUMAT\n0 $NPERM $EPSTAB 0 0\n\n" >> $vdWInput	
+																																																										#### write input-file for bin.ASV.1.3.11.linux64.intel (vdW-volume)
+																																																										Radii=$(cat $RadiiLib | sed '1d' | awk '{print $2 "=" $3}')
+																																																										echo -e "XYZ\n$XYZFILE\n1" > $vdWInput			### Specify Input-File
+																																																										echo $Radii >> $vdWInput						### read vdW-Radii from Library
+																																																										echo -e "$NUMAT\n0 $NPERM $EPSTAB 0 0\n\n" >> $vdWInput	
 
-bin.ASV.1.3.11.linux64.intel < $vdWInput > $vdWOutput 
+																																																										bin.ASV.1.3.11.linux64.intel < $vdWInput > $vdWOutput 
 
-Vol_vdW=($(grep 'V ='  $vdWOutput | awk '{print $3}')) #### all results of analytical vdW-volume calculation
-echo "${#Vol_vdW[@]} analytical vdW-Volume calculations of $FILE were carried out (EPSTAB=$EPSTAB):"
-CHECK='NOBST , NPERM , EPSTAB , ILIST ?'
-grep -B $NUMAT "$CHECK" $vdWOutput | head -"$NUMAT"	### List of read coordinates with vdW-radii
+																																																										Vol_vdW=($(grep 'V ='  $vdWOutput | awk '{print $3}')) #### all results of analytical vdW-volume calculation
+																																																										echo "${#Vol_vdW[@]} analytical vdW-Volume calculations of $FILE were carried out (EPSTAB=$EPSTAB):"
+																																																										CHECK='NOBST , NPERM , EPSTAB , ILIST ?'
+																																																										grep -B $NUMAT "$CHECK" $vdWOutput | head -"$NUMAT"	### List of read coordinates with vdW-radii
 
-if cat $vdWOutput | sed 's/ //g' | grep -q "Atom[0-9]hasRADIUS=0.000"; then
-	echo -e "\033[31mERROR! Assignment of vdW-Radii failed!\nPlease check $LOGFILE\nAborting.\033[0m"
-	grep 'RADIUS =' $vdWOutput
-	exit 10
-fi
+																																																										if cat $vdWOutput | sed 's/ //g' | grep -q "Atom[0-9]hasRADIUS=0.000"; then
+																																																												echo -e "\033[31mERROR! Assignment of vdW-Radii failed!\nPlease check $LOGFILE\nAborting.\033[0m"
+																																																													grep 'RADIUS =' $vdWOutput
+																																																														exit 10
+																																																													fi
 
-helpvar=$(echo ${Vol_vdW[@]} | sed 's/ /,/g')
+																																																													helpvar=$(echo ${Vol_vdW[@]} | sed 's/ /,/g')
 
-#### LOGFILE containing Input and Output
-	LOGFILE=$(echo "log-calcVolume_vdW-"$XYZFILE".txt" | sed 's/.xyz//')
-	echo "Input:" > $LOGFILE
-	cat $vdWInput >> $LOGFILE
-	echo "Output:" >> $LOGFILE
-	cat $vdWOutput >> $LOGFILE
-	echo "Analaysis of numberical instabilities:" >> $LOGFILE
-	analyzeGBV -i $helpvar -t 0.001 >> $LOGFILE
-	rm $vdWInput $vdWOutput
-####
+																																																													#### LOGFILE containing Input and Output
+																																																														LOGFILE=$(echo "log-calcVolume_vdW-"$XYZFILE".txt" | sed 's/.xyz//')
+																																																															echo "Input:" > $LOGFILE
+																																																																cat $vdWInput >> $LOGFILE
+																																																																	echo "Output:" >> $LOGFILE
+																																																																		cat $vdWOutput >> $LOGFILE
+																																																																			echo "Analaysis of numberical instabilities:" >> $LOGFILE
+																																																																				analyzeGBV -i $helpvar -t 0.001 >> $LOGFILE
+																																																																					rm $vdWInput $vdWOutput
+																																																																					####
 
-#### OUTPUT
+																																																																					#### OUTPUT
 
-if grep -q "Quality: 1" $LOGFILE; then
-	avgVol_vdW=$(tail -1 $LOGFILE | awk '{print $NF}')	### final result
-	echo -e "vdW-Volume (in Ang**3) of $FILE is: $avgVol_vdW"
-else
-	tail -1 $LOGFILE
-	echo -e "Analaysis of the vdW-Volume failed. There might be instabilities\nPlease check $LOGFILE\nAborting."
-	exit 10
-fi
+																																																																					if grep -q "Quality: 1" $LOGFILE; then
+																																																																							avgVol_vdW=$(tail -1 $LOGFILE | awk '{print $NF}')	### final result
+																																																																								echo -e "vdW-Volume (in Ang**3) of $FILE is: $avgVol_vdW"
+																																																																							else
+																																																																									tail -1 $LOGFILE
+																																																																										echo -e "Analaysis of the vdW-Volume failed. There might be instabilities\nPlease check $LOGFILE\nAborting."
+																																																																											exit 10
+																																																																										fi
 
 
 
-# benchmark: for i in 9 10 103; do if ls ./"$i"_*.xyz 1> /dev/null 2>&1; then for E in 0; do calcVolume_vdW -f "$i"_*.xyz -E "$E"; error=$(tac log-calcVolume_vdW-"$i"_*.txt | grep -m1 "MAE:" | awk '{print $NF}'); Vol=$(tail -1 log-calcVolume_vdW-"$i"_*.txt | awk '{print $1}'); echo $i $E $Vol $error; done; fi done
-# set up reference library: for i in *.xyz; do calcVolume_vdW $i >> all-data-reference-library_PBE0D3BJ_def2TZVPP_NPERM50_EPSTAB5E-6.txt; done
-# results references: for i in {1..185}; do FILE="log-calcVolume_vdW-"$i"_*.txt"; if [ -f $FILE ]; then if grep -q "Quality: 1" $FILE; then VOL=$(tail -1 $FILE); echo $i $VOL >> results-reference-library_PBE0D3BJ_def2SVP_NPERM50_EPSTAB5E-6.txt; fi; fi; done
+																																																																										# benchmark: for i in 9 10 103; do if ls ./"$i"_*.xyz 1> /dev/null 2>&1; then for E in 0; do calcVolume_vdW -f "$i"_*.xyz -E "$E"; error=$(tac log-calcVolume_vdW-"$i"_*.txt | grep -m1 "MAE:" | awk '{print $NF}'); Vol=$(tail -1 log-calcVolume_vdW-"$i"_*.txt | awk '{print $1}'); echo $i $E $Vol $error; done; fi done
+																																																																										# set up reference library: for i in *.xyz; do calcVolume_vdW $i >> all-data-reference-library_PBE0D3BJ_def2TZVPP_NPERM50_EPSTAB5E-6.txt; done
+																																																																										# results references: for i in {1..185}; do FILE="log-calcVolume_vdW-"$i"_*.txt"; if [ -f $FILE ]; then if grep -q "Quality: 1" $FILE; then VOL=$(tail -1 $FILE); echo $i $VOL >> results-reference-library_PBE0D3BJ_def2SVP_NPERM50_EPSTAB5E-6.txt; fi; fi; done
+
 
diff --git a/readSolventLibrary b/readSolventLibrary
--- a/readSolventLibrary
+++ b/readSolventLibrary
@@ -30,53 +30,54 @@ SEARCH2=$(cat $LibSolvent | awk -v  col2=$col_name '{print $col2}') ### column w
 
 while getopts "h" OPTION
 do
-    case $OPTION in
-		h)
-			if [[ -f $PATHSCRIPTS/help_readSolventLibrary.txt ]]; then
-				cat "$PATHSCRIPTS/help_readSolventLibrary.txt" 
-			else
-				echo "Help-File does not exist (yet)".
-			fi				
-			exit 10
-		;;
-		*)
-			echo -e "Nonexistent flag.\033[31m Aborting.\033[0m"
-			exit 10
-		;;
-    esac
-done 
+	    case $OPTION in
+		    		h)
+								if [[ -f $PATHSCRIPTS/help_readSolventLibrary.txt ]]; then
+													cat "$PATHSCRIPTS/help_readSolventLibrary.txt" 
+																else
+																					echo "Help-File does not exist (yet)".
+																								fi				
+																											exit 10
+																													;;
+																															*)
+																																			echo -e "Nonexistent flag.\033[31m Aborting.\033[0m"
+																																						exit 10
+																																								;;
+																																								    esac
+																																							    done 
 
-###### check Input: Either running number (Integer) or Name
-INPUT=$(echo $1 | sed 's/^0*//')	# remove leading zeros
-if [[ $(echo $INPUT | awk '{print NF}') -ne 1 ]]; then
-	echo "Invalid Input-Format. Please provide one entry at a time (Name or Number). Aborting."
-	exit 128
-fi
+																																							    ###### check Input: Either running number (Integer) or Name
+																																							    INPUT=$(echo $1 | sed 's/^0*//')	# remove leading zeros
+																																							    if [[ $(echo $INPUT | awk '{print NF}') -ne 1 ]]; then
+																																								    	echo "Invalid Input-Format. Please provide one entry at a time (Name or Number). Aborting."
+																																										exit 128
+																																									fi
 
-if [[ $(echo "$SEARCH1" | grep -x -c "$INPUT") -eq 1 ]]; then	### Search for Number with exact match
-	TARGET=$(echo "$SEARCH1" | grep -n -x "$INPUT" | cut -f1 -d':')
-elif [[ $(echo "$SEARCH2" | grep -i -w -c "$INPUT") -eq 1 ]]; then	### Search for Name with match 
-	TARGET=$(echo "$SEARCH2" | grep -i -n -w "$INPUT" | cut -f1 -d':')
-elif [[ $(echo "$SEARCH2" | grep -i -x -c "$INPUT") -eq 1 ]]; then	### Search for Name with exact match
-	TARGET=$(echo "$SEARCH2" | grep -i -n -x "$INPUT" | cut -f1 -d':')
-else
-	echo "Specified Solvent $INPUT is not unique or is not yet included."
-	grep -i "$INPUT" $LibSolvent
-	echo "Aborting."
-	exit 10
-fi
+																																									if [[ $(echo "$SEARCH1" | grep -x -c "$INPUT") -eq 1 ]]; then	### Search for Number with exact match
+																																											TARGET=$(echo "$SEARCH1" | grep -n -x "$INPUT" | cut -f1 -d':')
+																																										elif [[ $(echo "$SEARCH2" | grep -i -w -c "$INPUT") -eq 1 ]]; then	### Search for Name with match 
+																																												TARGET=$(echo "$SEARCH2" | grep -i -n -w "$INPUT" | cut -f1 -d':')
+																																											elif [[ $(echo "$SEARCH2" | grep -i -x -c "$INPUT") -eq 1 ]]; then	### Search for Name with exact match
+																																													TARGET=$(echo "$SEARCH2" | grep -i -n -x "$INPUT" | cut -f1 -d':')
+																																												else
+																																														echo "Specified Solvent $INPUT is not unique or is not yet included."
+																																															grep -i "$INPUT" $LibSolvent
+																																																echo "Aborting."
+																																																	exit 10
+																																																fi
 
-echo "Requested solvent: $INPUT"
-#### from now on INPUT is unique and legit
+																																																echo "Requested solvent: $INPUT"
+																																																#### from now on INPUT is unique and legit
 
 
-##### READ DATA
-HIT=$(sed -n "$TARGET"p $LibSolvent)
-Solvent=$(echo "$HIT" | awk -v col=$col_name '{print $col}')
-Permitivity=$(echo "$HIT" | awk -v col=$col_P '{print $col}')
-MolarMass=$(echo "$HIT" | awk -v col=$col_M '{print $col}')
-Density=$(echo "$HIT" | awk -v col=$col_D '{print $col}')
-vdW_Volume=$(echo "$HIT" | awk -v col=$col_V '{print $col}')
+																																																##### READ DATA
+																																																HIT=$(sed -n "$TARGET"p $LibSolvent)
+																																																Solvent=$(echo "$HIT" | awk -v col=$col_name '{print $col}')
+																																																Permitivity=$(echo "$HIT" | awk -v col=$col_P '{print $col}')
+																																																MolarMass=$(echo "$HIT" | awk -v col=$col_M '{print $col}')
+																																																Density=$(echo "$HIT" | awk -v col=$col_D '{print $col}')
+																																																vdW_Volume=$(echo "$HIT" | awk -v col=$col_V '{print $col}')
 
-#### Output
-echo -e "Solvent data for $Solvent:\nPermitivity $Permitivity\nMolarMass $MolarMass\nDensity $Density\nvdW-Volume $vdW_Volume"
+																																																#### Output
+																																																echo -e "Solvent data for $Solvent:\nPermitivity $Permitivity\nMolarMass $MolarMass\nDensity $Density\nvdW-Volume $vdW_Volume"
+
